ALTER TABLE `gossip_menu` MODIFY COLUMN `entry`  int(11) UNSIGNED NOT NULL DEFAULT 0 FIRST;
ALTER TABLE `gossip_menu_option` MODIFY COLUMN `menu_id`  int(11) UNSIGNED NOT NULL DEFAULT 0 FIRST;
ALTER TABLE `locales_gossip_menu_option` MODIFY COLUMN `menu_id`  int(11) UNSIGNED NOT NULL DEFAULT 0 FIRST;

