ALTER TABLE characters MODIFY power1 int(10) NOT NULL DEFAULT '0';
ALTER TABLE characters MODIFY power2 int(10) NOT NULL DEFAULT '0';
ALTER TABLE characters MODIFY power3 int(10) NOT NULL DEFAULT '0';
ALTER TABLE characters MODIFY power4 int(10) NOT NULL DEFAULT '0';
