DROP TABLE IF EXISTS blackmarket;
CREATE TABLE blackmarket (
  id INT UNSIGNED NOT NULL,
  templateId INT UNSIGNED NOT NULL,
  startTime INT UNSIGNED NOT NULL,
  bid BIGINT UNSIGNED NOT NULL,
  bidder INT UNSIGNED NOT NULL,
  bidderCount INT UNSIGNED NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 ROW_FORMAT=DYNAMIC;
