DROP TABLE IF EXISTS `auctionhouse`;
CREATE TABLE `auctionhouse` (
  `id` INT UNSIGNED NOT NULL DEFAULT 0,
  `auctionHouseId` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `itemguid` INT UNSIGNED NOT NULL DEFAULT 0,
  `itemowner` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `buyoutprice` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `time` INT UNSIGNED NOT NULL DEFAULT 0,
  `buyguid` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `lastbid` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `startbid` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `deposit` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `item_guid` (`itemguid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `guild_bank_eventlog`
  MODIFY COLUMN `ItemOrMoney` BIGINT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE `account_achievement_progress`
  MODIFY COLUMN `counter` BIGINT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE `character_achievement_progress`
  MODIFY COLUMN `counter` BIGINT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE `guild_achievement_progress`
  MODIFY COLUMN `counter` BIGINT UNSIGNED NOT NULL DEFAULT 0;
