-- instances and raids
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 33, 15, 'Shadowfang Keep');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 34, 15, 'Stormwind Stockade');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 36, 15, 'Deadmines');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 43, 15, 'Wailing Caverns');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 44, 15, '<unused> Monastery');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 47, 15, 'Razorfen Kraul');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 48, 15, 'Blackfathom Deeps');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 70, 15, 'Uldaman');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 90, 15, 'Gnomeregan');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 109, 15, 'Sunken Temple');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 129, 15, 'Razorfen Downs');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 169, 15, 'Emerald Dream');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 189, 15, 'Scarlet Monastery of Old');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 209, 15, 'Zul''Farrak');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 229, 15, 'Blackrock Spire');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 230, 15, 'Blackrock Depths');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 249, 15, 'Onyxia''s Lair');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 269, 15, 'Opening of the Dark Portal');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 289, 15, 'Scholomance OLD');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 309, 15, 'Ancient Zul''Gurub');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 329, 15, 'Stratholme');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 349, 15, 'Maraudon');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 389, 15, 'Ragefire Chasm');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 409, 15, 'Molten Core');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 429, 15, 'Dire Maul');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 469, 15, 'Blackwing Lair');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 509, 15, 'Ruins of Ahn''Qiraj');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 531, 15, 'Ahn''Qiraj Temple');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 532, 15, 'Karazhan');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 533, 15, 'Naxxramas');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 534, 15, 'The Battle for Mount Hyjal');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 540, 15, 'Hellfire Citadel: The Shattered Halls');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 542, 15, 'Hellfire Citadel: The Blood Furnace');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 543, 15, 'Hellfire Citadel: Ramparts');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 544, 15, 'Magtheridon''s Lair');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 545, 15, 'Coilfang: The Steamvault');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 546, 15, 'Coilfang: The Underbog');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 547, 15, 'Coilfang: The Slave Pens');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 548, 15, 'Coilfang: Serpentshrine Cavern');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 550, 15, 'Tempest Keep');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 552, 15, 'Tempest Keep: The Arcatraz');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 553, 15, 'Tempest Keep: The Botanica');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 554, 15, 'Tempest Keep: The Mechanar');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 555, 15, 'Auchindoun: Shadow Labyrinth');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 556, 15, 'Auchindoun: Sethekk Halls');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 557, 15, 'Auchindoun: Mana-Tombs');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 558, 15, 'Auchindoun: Auchenai Crypts');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 560, 15, 'The Escape From Durnholde');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 564, 15, 'Black Temple');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 565, 15, 'Gruul''s Lair');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 568, 15, 'Zul''Aman');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 574, 15, 'Utgarde Keep');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 575, 15, 'Utgarde Pinnacle');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 576, 15, 'The Nexus');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 578, 15, 'The Oculus');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 580, 15, 'The Sunwell');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 585, 15, 'Magister''s Terrace');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 595, 15, 'The Culling of Stratholme');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 598, 15, 'Sunwell Fix (Unused)');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 599, 15, 'Halls of Stone');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 600, 15, 'Drak''Tharon Keep');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 601, 15, 'Azjol-Nerub');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 602, 15, 'Halls of Lightning');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 603, 15, 'Ulduar');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 604, 15, 'Gundrak');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 608, 15, 'Violet Hold');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 615, 15, 'The Obsidian Sanctum');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 616, 15, 'The Eye of Eternity');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 619, 15, 'Ahn''kahet: The Old Kingdom');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 624, 15, 'Vault of Archavon');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 627, 15, 'unused');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 631, 15, 'Icecrown Citadel');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 632, 15, 'The Forge of Souls');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 637, 15, 'Abyssal Maw Exterior');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 643, 15, 'Throne of the Tides');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 644, 15, 'Halls of Origination');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 645, 15, 'Blackrock Caverns');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 649, 15, 'Trial of the Crusader');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 650, 15, 'Trial of the Champion');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 657, 15, 'The Vortex Pinnacle');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 658, 15, 'Pit of Saron');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 668, 15, 'Halls of Reflection');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 669, 15, 'Blackwing Descent');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 670, 15, 'Grim Batol');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 671, 15, 'The Bastion of Twilight');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 720, 15, 'Firelands');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 721, 15, 'Firelands Terrain 2');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 724, 15, 'The Ruby Sanctum');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 725, 15, 'The Stonecore');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 728, 15, 'The Battle for Gilneas (Old City Map)');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 734, 15, 'Ahn''Qiraj Terrace');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 754, 15, 'Throne of the Four Winds');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 755, 15, 'Lost City of the Tol''vir');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 757, 15, 'Baradin Hold');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 859, 15, 'Zul''Gurub');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 930, 15, '(UNUSED) Scenario: Alcaz Island');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 938, 15, 'End Time');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 939, 15, 'Well of Eternity');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 940, 15, 'Hour of Twilight');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 951, 15, 'Nexus Legendary');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 959, 15, 'Shado-Pan Monastery');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 960, 15, 'Temple of the Jade Serpent');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 961, 15, 'Stormstout Brewery');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 962, 15, 'Gate of the Setting Sun');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 967, 15, 'Dragon Soul');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 977, 15, 'Maelstrom Deathwing Fight');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 994, 15, 'Mogu''shan Palace');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 995, 15, 'The Depths [UNUSED]');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 996, 15, 'Terrace of Endless Spring');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 999, 15, 'Theramore''s Fall (H)');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1000, 15, 'Theramore''s Fall (A)');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1001, 15, 'Scarlet Halls');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1004, 15, 'Scarlet Monastery');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1005, 15, 'A Brewing Storm');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1007, 15, 'Scholomance');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1008, 15, 'Mogu''shan Vaults');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1009, 15, 'Heart of Fear');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1011, 15, 'Siege of Niuzao Temple');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1014, 15, '(UNUSED) Peak of Serenity Scenario');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1024, 15, 'Greenstone Village');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1028, 15, '(UNUSED) Scenario: Mogu Ruins');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1029, 15, '(UNUSED) Scenario: Mogu Crypt');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1030, 15, 'Crypt of Forgotten Kings');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1031, 15, 'Arena of Annihilation');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1032, 15, 'Pet Battle - Jade Forest');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1035, 15, 'Temple of Kotmogu');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1048, 15, 'Unga Ingoo');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1049, 15, '(UNUSED) Scenario: Black Ox Temple');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1050, 15, 'Assault on Zan''vess');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1051, 15, 'Brewmoon Festival');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1095, 15, 'Dagger in the Dark');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1098, 15, 'Throne of Thunder');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1099, 15, 'Naval Battle Scenario');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1102, 15, 'Domination Point');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1103, 15, 'Lion''s Landing');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1104, 15, 'A Little Patience');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1112, 15, 'Pursuing the Black Harvest');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1122, 15, 'City Siege - Mogu Island Progression Scenario');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1123, 15, 'Lightning Forge - Mogu Island Progression Scenario');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1124, 15, 'Shipyard - Mogu Island Progression Scenario');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1125, 15, 'Alliance Hub - Mogu Island Progression Scenario');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1126, 15, 'Mogu Island Progression Events');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1127, 15, 'Final Gate - Mogu Island Progression Scenario');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1130, 15, 'Blood in the Snow');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1131, 15, 'The Secrets of Ragefire');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1135, 15, 'Mogu Island Loot Room');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1136, 15, 'Siege of Orgrimmar');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1144, 15, 'Heart of the Old God Scenario');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1148, 15, 'Proving Grounds');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1155, 15, 'Stromgarde Keep');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1157, 15, 'Halfhill Scenario');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (2, 1161, 15, 'Celestial Tournament');

-- battlegrounds and arenas
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 1,   0, 'BATTLEGROUND_AV');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 2,   0, 'BATTLEGROUND_WS');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 3,   0, 'BATTLEGROUND_AB');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 4,   0, 'BATTLEGROUND_NA');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 5,   0, 'BATTLEGROUND_BE');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 6,   0, 'BATTLEGROUND_AA');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 7,   0, 'BATTLEGROUND_EY');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 8,   0, 'BATTLEGROUND_RL');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 9,   0, 'BATTLEGROUND_SA');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 10,  0, 'BATTLEGROUND_DS');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 11,  0, 'BATTLEGROUND_RV');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 30,  0, 'BATTLEGROUND_IC');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 32,  0, 'BATTLEGROUND_RB');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 100, 0, 'BATTLEGROUND_RATED_10_VS_10');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 101, 0, 'BATTLEGROUND_RATED_15_VS_15');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 102, 0, 'BATTLEGROUND_RATED_25_VS_25');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 108, 0, 'BATTLEGROUND_TP');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 120, 0, 'BATTLEGROUND_BFG');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 699, 0, 'BATTLEGROUND_KT');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 706, 0, 'BATTLEGROUND_CTF3');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 708, 0, 'BATTLEGROUND_SSM');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 719, 0, 'BATTLEGROUND_TV');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 754, 0, 'BATTLEGROUND_DG');
REPLACE INTO disables (sourceType, entry, flags, `comment`) VALUES (3, 757, 0, 'BATTLEGROUND_TTP');
