-- [SQL] Quests - Profession quests requirements corrected (Feedback #3155)
UPDATE `quest_template` SET `RequiredSkillPoints` = 1 WHERE `RequiredSkillId` > 0 AND `RequiredSkillPoints` = 0;
UPDATE `quest_template` SET `RequiredSkillId` = 185, `RequiredSkillPoints` = 1 WHERE `Id` = 90;
UPDATE `quest_template` SET `RequiredSkillId` = 356, `RequiredSkillPoints` = 1 WHERE `Id` = 1141;
UPDATE `quest_template` SET `RequiredSkillId` = 186, `RequiredSkillPoints` = 230 WHERE `Id` = 4083;
UPDATE `quest_template` SET `RequiredSkillId` = 165, `RequiredSkillPoints` = 1 WHERE `Id` = 7384;
UPDATE `quest_template` SET `RequiredSkillId` = 197, `RequiredSkillPoints` = 1 WHERE `Id` = 11088;
UPDATE `quest_template` SET `RequiredSkillId` = 202, `RequiredSkillPoints` = 400 WHERE `Id` = 12889;
UPDATE `quest_template` SET `RequiredSkillId` = 197, `RequiredSkillPoints` = 1 WHERE `Id` = 13303;
UPDATE `quest_template` SET `RequiredSkillId` = 202, `RequiredSkillPoints` = 1 WHERE `Id` = 13843;
UPDATE `quest_template` SET `RequiredSkillId` = 773, `RequiredSkillPoints` = 1 WHERE `Id` = 27675;
UPDATE `quest_template` SET `RequiredSkillId` = 773, `RequiredSkillPoints` = 1 WHERE `Id` = 27686;
UPDATE `quest_template` SET `RequiredSkillId` = 171, `RequiredSkillPoints` = 75 WHERE `Id` = 29506;
UPDATE `quest_template` SET `RequiredSkillId` = 164, `RequiredSkillPoints` = 75 WHERE `Id` = 29508;
UPDATE `quest_template` SET `RequiredSkillId` = 185, `RequiredSkillPoints` = 75 WHERE `Id` = 29509;
UPDATE `quest_template` SET `RequiredSkillId` = 333, `RequiredSkillPoints` = 75 WHERE `Id` = 29510;
UPDATE `quest_template` SET `RequiredSkillId` = 202, `RequiredSkillPoints` = 75 WHERE `Id` = 29511;
UPDATE `quest_template` SET `RequiredSkillId` = 129, `RequiredSkillPoints` = 75 WHERE `Id` = 29512;
UPDATE `quest_template` SET `RequiredSkillId` = 356, `RequiredSkillPoints` = 75 WHERE `Id` = 29513;
UPDATE `quest_template` SET `RequiredSkillId` = 182, `RequiredSkillPoints` = 75 WHERE `Id` = 29514;
UPDATE `quest_template` SET `RequiredSkillId` = 773, `RequiredSkillPoints` = 75 WHERE `Id` = 29515;
UPDATE `quest_template` SET `RequiredSkillId` = 755, `RequiredSkillPoints` = 75 WHERE `Id` = 29516;
UPDATE `quest_template` SET `RequiredSkillId` = 165, `RequiredSkillPoints` = 75 WHERE `Id` = 29517;
UPDATE `quest_template` SET `RequiredSkillId` = 186, `RequiredSkillPoints` = 75 WHERE `Id` = 29518;
UPDATE `quest_template` SET `RequiredSkillId` = 393, `RequiredSkillPoints` = 75 WHERE `Id` = 29519;
UPDATE `quest_template` SET `RequiredSkillId` = 197, `RequiredSkillPoints` = 75 WHERE `Id` = 29520;
UPDATE `quest_template` SET `RequiredSkillId` = 182, `RequiredSkillPoints` = 50 WHERE `Id` = 866;
UPDATE `quest_template` SET `RequiredSkillId` = 202, `RequiredSkillPoints` = 185 WHERE `Id` = 1559;
UPDATE `quest_template` SET `RequiredSkillId` = 171, `RequiredSkillPoints` = 210 WHERE `Id` = 2203;
UPDATE `quest_template` SET `RequiredSkillId` = 164, `RequiredSkillPoints` = 135 WHERE `Id` = 2752;
UPDATE `quest_template` SET `RequiredSkillId` = 164, `RequiredSkillPoints` = 170 WHERE `Id` = 2753;
UPDATE `quest_template` SET `RequiredSkillId` = 164, `RequiredSkillPoints` = 155 WHERE `Id` = 2754;
UPDATE `quest_template` SET `RequiredSkillId` = 164, `RequiredSkillPoints` = 215 WHERE `Id` = 2755;
UPDATE `quest_template` SET `RequiredSkillId` = 202, `RequiredSkillPoints` = 250 WHERE `Id` = 8798;
UPDATE `quest_template` SET `RequiredSkillId` = 164, `RequiredSkillPoints` = 200 WHERE `Id` = 8869;
UPDATE `quest_template` SET `RequiredSkillId` = 356, `RequiredSkillPoints` = 275 WHERE `Id` = 11531;
UPDATE `quest_template` SET `RequiredSkillId` = 356, `RequiredSkillPoints` = 275 WHERE `Id` = 11665;
UPDATE `quest_template` SET `RequiredSkillId` = 356, `RequiredSkillPoints` = 275 WHERE `Id` = 11666;
UPDATE `quest_template` SET `RequiredSkillId` = 356, `RequiredSkillPoints` = 275 WHERE `Id` = 11667;
UPDATE `quest_template` SET `RequiredSkillId` = 356, `RequiredSkillPoints` = 275 WHERE `Id` = 11668;
UPDATE `quest_template` SET `RequiredSkillId` = 356, `RequiredSkillPoints` = 275 WHERE `Id` = 11669;
UPDATE `quest_template` SET `RequiredSkillId` = 356, `RequiredSkillPoints` = 225 WHERE `Id` = 13826;
UPDATE `quest_template` SET `RequiredSkillId` = 356, `RequiredSkillPoints` = 350 WHERE `Id` = 13830;
UPDATE `quest_template` SET `RequiredSkillId` = 356, `RequiredSkillPoints` = 350 WHERE `Id` = 13832;
UPDATE `quest_template` SET `RequiredSkillId` = 356, `RequiredSkillPoints` = 350 WHERE `Id` = 13833;
UPDATE `quest_template` SET `RequiredSkillId` = 356, `RequiredSkillPoints` = 350 WHERE `Id` = 13834;
UPDATE `quest_template` SET `RequiredSkillId` = 356, `RequiredSkillPoints` = 350 WHERE `Id` = 13836;
UPDATE `quest_template` SET `RequiredSkillId` = 755, `RequiredSkillPoints` = 475 WHERE `Id` = 25047;
UPDATE `quest_template` SET `RequiredSkillId` = 755, `RequiredSkillPoints` = 475 WHERE `Id` = 25105;
UPDATE `quest_template` SET `RequiredSkillId` = 755, `RequiredSkillPoints` = 475 WHERE `Id` = 25154;
UPDATE `quest_template` SET `RequiredSkillId` = 755, `RequiredSkillPoints` = 475 WHERE `Id` = 25155;
UPDATE `quest_template` SET `RequiredSkillId` = 755, `RequiredSkillPoints` = 475 WHERE `Id` = 25156;
UPDATE `quest_template` SET `RequiredSkillId` = 755, `RequiredSkillPoints` = 475 WHERE `Id` = 25157;
UPDATE `quest_template` SET `RequiredSkillId` = 755, `RequiredSkillPoints` = 475 WHERE `Id` = 25158;
UPDATE `quest_template` SET `RequiredSkillId` = 755, `RequiredSkillPoints` = 475 WHERE `Id` = 25159;
UPDATE `quest_template` SET `RequiredSkillId` = 755, `RequiredSkillPoints` = 475 WHERE `Id` = 25160;
UPDATE `quest_template` SET `RequiredSkillId` = 755, `RequiredSkillPoints` = 475 WHERE `Id` = 25161;
UPDATE `quest_template` SET `RequiredSkillId` = 755, `RequiredSkillPoints` = 475 WHERE `Id` = 25162;
UPDATE `quest_template` SET `RequiredSkillId` = 755, `RequiredSkillPoints` = 475 WHERE `Id` = 28775;
UPDATE `quest_template` SET `RequiredSkillId` = 755, `RequiredSkillPoints` = 475 WHERE `Id` = 28776;
UPDATE `quest_template` SET `RequiredSkillId` = 755, `RequiredSkillPoints` = 475 WHERE `Id` = 28777;
UPDATE `quest_template` SET `RequiredSkillId` = 755, `RequiredSkillPoints` = 475 WHERE `Id` = 28778;
UPDATE `quest_template` SET `RequiredSkillId` = 794, `RequiredSkillPoints` = 425 WHERE `Id` = 28798;
UPDATE `quest_template` SET `RequiredSkillId` = 794, `RequiredSkillPoints` = 425 WHERE `Id` = 28799;
UPDATE `quest_template` SET `RequiredSkillId` = 794, `RequiredSkillPoints` = 425 WHERE `Id` = 28800;
UPDATE `quest_template` SET `RequiredSkillId` = 794, `RequiredSkillPoints` = 425 WHERE `Id` = 28801;
UPDATE `quest_template` SET `RequiredSkillId` = 794, `RequiredSkillPoints` = 425 WHERE `Id` = 28802;
UPDATE `quest_template` SET `RequiredSkillId` = 794, `RequiredSkillPoints` = 425 WHERE `Id` = 28803;
UPDATE `quest_template` SET `RequiredSkillId` = 794, `RequiredSkillPoints` = 425 WHERE `Id` = 28804;
UPDATE `quest_template` SET `RequiredSkillId` = 773, `RequiredSkillPoints` = 75 WHERE `Id` = 29261;
UPDATE `quest_template` SET `RequiredSkillId` = 773, `RequiredSkillPoints` = 75 WHERE `Id` = 29262;
UPDATE `quest_template` SET `RequiredSkillId` = 202, `RequiredSkillPoints` = 200 WHERE `Id` = 29475;
UPDATE `quest_template` SET `RequiredSkillId` = 202, `RequiredSkillPoints` = 200 WHERE `Id` = 29476;
UPDATE `quest_template` SET `RequiredSkillId` = 202, `RequiredSkillPoints` = 200 WHERE `Id` = 29477;
-- [SQL] Quests - 114 quests will now have correct class requirements
UPDATE `quest_template` SET `RequiredClasses` = 1279 WHERE `Id` = 792;
UPDATE `quest_template` SET `RequiredClasses` = 1 WHERE `Id` = 1782;
UPDATE `quest_template` SET `RequiredClasses` = 1 WHERE `Id` = 3100;
UPDATE `quest_template` SET `RequiredClasses` = 2 WHERE `Id` = 3101;
UPDATE `quest_template` SET `RequiredClasses` = 8 WHERE `Id` = 3102;
UPDATE `quest_template` SET `RequiredClasses` = 16 WHERE `Id` = 3103;
UPDATE `quest_template` SET `RequiredClasses` = 128 WHERE `Id` = 3104;
UPDATE `quest_template` SET `RequiredClasses` = 256 WHERE `Id` = 3105;
UPDATE `quest_template` SET `RequiredClasses` = 64 WHERE `Id` = 8188;
UPDATE `quest_template` SET `RequiredClasses` = 128 WHERE `Id` = 8189;
UPDATE `quest_template` SET `RequiredClasses` = 256 WHERE `Id` = 8190;
UPDATE `quest_template` SET `RequiredClasses` = 16 WHERE `Id` = 8191;
UPDATE `quest_template` SET `RequiredClasses` = 1024 WHERE `Id` = 8192;
UPDATE `quest_template` SET `RequiredClasses` = 16 WHERE `Id` = 8379;
UPDATE `quest_template` SET `RequiredClasses` = 64 WHERE `Id` = 8380;
UPDATE `quest_template` SET `RequiredClasses` = 128 WHERE `Id` = 8381;
UPDATE `quest_template` SET `RequiredClasses` = 1024 WHERE `Id` = 8382;
UPDATE `quest_template` SET `RequiredClasses` = 129 WHERE `Id` = 8962;
UPDATE `quest_template` SET `RequiredClasses` = 1280 WHERE `Id` = 8963;
UPDATE `quest_template` SET `RequiredClasses` = 12 WHERE `Id` = 8964;
UPDATE `quest_template` SET `RequiredClasses` = 82 WHERE `Id` = 8965;
UPDATE `quest_template` SET `RequiredClasses` = 129 WHERE `Id` = 8966;
UPDATE `quest_template` SET `RequiredClasses` = 1280 WHERE `Id` = 8967;
UPDATE `quest_template` SET `RequiredClasses` = 12 WHERE `Id` = 8968;
UPDATE `quest_template` SET `RequiredClasses` = 82 WHERE `Id` = 8969;
UPDATE `quest_template` SET `RequiredClasses` = 1090 WHERE `Id` = 8986;
UPDATE `quest_template` SET `RequiredClasses` = 144 WHERE `Id` = 8987;
UPDATE `quest_template` SET `RequiredClasses` = 260 WHERE `Id` = 8988;
UPDATE `quest_template` SET `RequiredClasses` = 1090 WHERE `Id` = 8989;
UPDATE `quest_template` SET `RequiredClasses` = 9 WHERE `Id` = 8990;
UPDATE `quest_template` SET `RequiredClasses` = 144 WHERE `Id` = 8991;
UPDATE `quest_template` SET `RequiredClasses` = 260 WHERE `Id` = 8992;
UPDATE `quest_template` SET `RequiredClasses` = 64 WHERE `Id` = 9068;
UPDATE `quest_template` SET `RequiredClasses` = 64 WHERE `Id` = 9069;
UPDATE `quest_template` SET `RequiredClasses` = 64 WHERE `Id` = 9070;
UPDATE `quest_template` SET `RequiredClasses` = 64 WHERE `Id` = 9071;
UPDATE `quest_template` SET `RequiredClasses` = 64 WHERE `Id` = 9072;
UPDATE `quest_template` SET `RequiredClasses` = 64 WHERE `Id` = 9073;
UPDATE `quest_template` SET `RequiredClasses` = 64 WHERE `Id` = 9074;
UPDATE `quest_template` SET `RequiredClasses` = 64 WHERE `Id` = 9075;
UPDATE `quest_template` SET `RequiredClasses` = 8 WHERE `Id` = 9078;
UPDATE `quest_template` SET `RequiredClasses` = 1024 WHERE `Id` = 9086;
UPDATE `quest_template` SET `RequiredClasses` = 1024 WHERE `Id` = 9087;
UPDATE `quest_template` SET `RequiredClasses` = 1024 WHERE `Id` = 9088;
UPDATE `quest_template` SET `RequiredClasses` = 1024 WHERE `Id` = 9089;
UPDATE `quest_template` SET `RequiredClasses` = 1024 WHERE `Id` = 9090;
UPDATE `quest_template` SET `RequiredClasses` = 1024 WHERE `Id` = 9091;
UPDATE `quest_template` SET `RequiredClasses` = 1024 WHERE `Id` = 9092;
UPDATE `quest_template` SET `RequiredClasses` = 1024 WHERE `Id` = 9093;
UPDATE `quest_template` SET `RequiredClasses` = 128 WHERE `Id` = 9095;
UPDATE `quest_template` SET `RequiredClasses` = 128 WHERE `Id` = 9096;
UPDATE `quest_template` SET `RequiredClasses` = 128 WHERE `Id` = 9097;
UPDATE `quest_template` SET `RequiredClasses` = 128 WHERE `Id` = 9098;
UPDATE `quest_template` SET `RequiredClasses` = 128 WHERE `Id` = 9099;
UPDATE `quest_template` SET `RequiredClasses` = 128 WHERE `Id` = 9100;
UPDATE `quest_template` SET `RequiredClasses` = 128 WHERE `Id` = 9101;
UPDATE `quest_template` SET `RequiredClasses` = 128 WHERE `Id` = 9102;
UPDATE `quest_template` SET `RequiredClasses` = 256 WHERE `Id` = 9103;
UPDATE `quest_template` SET `RequiredClasses` = 256 WHERE `Id` = 9104;
UPDATE `quest_template` SET `RequiredClasses` = 256 WHERE `Id` = 9105;
UPDATE `quest_template` SET `RequiredClasses` = 256 WHERE `Id` = 9106;
UPDATE `quest_template` SET `RequiredClasses` = 256 WHERE `Id` = 9107;
UPDATE `quest_template` SET `RequiredClasses` = 256 WHERE `Id` = 9108;
UPDATE `quest_template` SET `RequiredClasses` = 256 WHERE `Id` = 9109;
UPDATE `quest_template` SET `RequiredClasses` = 256 WHERE `Id` = 9110;
UPDATE `quest_template` SET `RequiredClasses` = 16 WHERE `Id` = 9111;
UPDATE `quest_template` SET `RequiredClasses` = 16 WHERE `Id` = 9112;
UPDATE `quest_template` SET `RequiredClasses` = 16 WHERE `Id` = 9113;
UPDATE `quest_template` SET `RequiredClasses` = 16 WHERE `Id` = 9114;
UPDATE `quest_template` SET `RequiredClasses` = 16 WHERE `Id` = 9115;
UPDATE `quest_template` SET `RequiredClasses` = 16 WHERE `Id` = 9116;
UPDATE `quest_template` SET `RequiredClasses` = 16 WHERE `Id` = 9117;
UPDATE `quest_template` SET `RequiredClasses` = 16 WHERE `Id` = 9118;
UPDATE `quest_template` SET `RequiredClasses` = 400 WHERE `Id` = 9238;
UPDATE `quest_template` SET `RequiredClasses` = 400 WHERE `Id` = 9239;
UPDATE `quest_template` SET `RequiredClasses` = 400 WHERE `Id` = 9240;
UPDATE `quest_template` SET `RequiredClasses` = 1032 WHERE `Id` = 9241;
UPDATE `quest_template` SET `RequiredClasses` = 1032 WHERE `Id` = 9242;
UPDATE `quest_template` SET `RequiredClasses` = 1032 WHERE `Id` = 9243;
UPDATE `quest_template` SET `RequiredClasses` = 68 WHERE `Id` = 9244;
UPDATE `quest_template` SET `RequiredClasses` = 68 WHERE `Id` = 9245;
UPDATE `quest_template` SET `RequiredClasses` = 68 WHERE `Id` = 9246;
UPDATE `quest_template` SET `RequiredClasses` = 32 WHERE `Id` = 12781;
UPDATE `quest_template` SET `RequiredClasses` = 1503 WHERE `Id` = 13408;
UPDATE `quest_template` SET `RequiredClasses` = 1503 WHERE `Id` = 13409;
UPDATE `quest_template` SET `RequiredClasses` = 1503 WHERE `Id` = 13682;
UPDATE `quest_template` SET `RequiredClasses` = 1503 WHERE `Id` = 13789;
UPDATE `quest_template` SET `RequiredClasses` = 1503 WHERE `Id` = 13790;
UPDATE `quest_template` SET `RequiredClasses` = 1503 WHERE `Id` = 13794;
UPDATE `quest_template` SET `RequiredClasses` = 1503 WHERE `Id` = 13809;
UPDATE `quest_template` SET `RequiredClasses` = 1503 WHERE `Id` = 13810;
UPDATE `quest_template` SET `RequiredClasses` = 1503 WHERE `Id` = 13811;
UPDATE `quest_template` SET `RequiredClasses` = 1503 WHERE `Id` = 13861;
UPDATE `quest_template` SET `RequiredClasses` = 1503 WHERE `Id` = 13862;
UPDATE `quest_template` SET `RequiredClasses` = 431 WHERE `Id` = 24553;
UPDATE `quest_template` SET `RequiredClasses` = 431 WHERE `Id` = 24564;
UPDATE `quest_template` SET `RequiredClasses` = 431 WHERE `Id` = 24594;
UPDATE `quest_template` SET `RequiredClasses` = 1104 WHERE `Id` = 24595;
UPDATE `quest_template` SET `RequiredClasses` = 16 WHERE `Id` = 24596;
UPDATE `quest_template` SET `RequiredClasses` = 1104 WHERE `Id` = 24598;
UPDATE `quest_template` SET `RequiredClasses` = 1104 WHERE `Id` = 24799;
UPDATE `quest_template` SET `RequiredClasses` = 4 WHERE `Id` = 25076;
UPDATE `quest_template` SET `RequiredClasses` = 4 WHERE `Id` = 25077;
UPDATE `quest_template` SET `RequiredClasses` = 4 WHERE `Id` = 25078;
UPDATE `quest_template` SET `RequiredClasses` = 4 WHERE `Id` = 25083;
UPDATE `quest_template` SET `RequiredClasses` = 256 WHERE `Id` = 25137;
UPDATE `quest_template` SET `RequiredClasses` = 4 WHERE `Id` = 25140;
UPDATE `quest_template` SET `RequiredClasses` = 8 WHERE `Id` = 25142;
UPDATE `quest_template` SET `RequiredClasses` = 64 WHERE `Id` = 25144;
UPDATE `quest_template` SET `RequiredClasses` = 256 WHERE `Id` = 25146;
UPDATE `quest_template` SET `RequiredClasses` = 1 WHERE `Id` = 25148;
UPDATE `quest_template` SET `RequiredClasses` = 128 WHERE `Id` = 25150;
UPDATE `quest_template` SET `RequiredClasses` = 256 WHERE `Id` = 26151;
UPDATE `quest_template` SET `RequiredClasses` = 8 WHERE `Id` = 30118;
-- SELECT RequiredClasses, Id FROM 434_world.quest_template WHERE RequiredClasses > 0 AND Id NOT IN (SELECT Id FROM 540_world.quest_template WHERE RequiredClasses > 0);
