DROP TABLE IF EXISTS `reserved_name`;
CREATE TABLE `reserved_name` (
  `name` varchar(12) NOT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='Player Reserved Names';

-- [SQL] [Internal] Added reserved names to world db
DELETE FROM `reserved_name`;
INSERT INTO `reserved_name` (`name`) VALUES
('admin'),
('aldtharios'),
('assistant'),
('blue'),
('borrean'),
('cairner'),
('cavah'),
('chemyst'),
('cognoscere'),
('creditcard'),
('developer'),
('edifice'),
('eventmaster'),
('freakz'),
('gackt'),
('gamemaster'),
('gmpower'),
('hermes'),
('kaer'),
('kosmokoz'),
('leona'),
('mastercard'),
('moderator'),
('molten'),
('moneybook'),
('mrgreen'),
('nepenthe'),
('neverendless'),
('octantis'),
('payment'),
('paypal'),
('proterean'),
('ramires'),
('raufen'),
('skrill'),
('support'),
('tester'),
('thedrift'),
('webmaster'),
('westernunion'),
('wow'),
('pandashan');